// かな -> ローマ字の対応表。MS-IME と Mozc (Google 日本語入力) の両方の
// 既定ローマ字テーブルで通る打ち方だけを載せる。各配列の先頭がガイド表示の既定。
// 「ん」と、子音を重ねる「っ」は文脈依存なので engine.ts 側で扱う。

const table: Record<string, string[]> = {
  あ: ['a'],
  い: ['i', 'yi'],
  う: ['u', 'wu', 'whu'],
  え: ['e'],
  お: ['o'],
  か: ['ka', 'ca'],
  き: ['ki'],
  く: ['ku', 'cu', 'qu'],
  け: ['ke'],
  こ: ['ko', 'co'],
  さ: ['sa'],
  し: ['si', 'shi', 'ci'],
  す: ['su'],
  せ: ['se', 'ce'],
  そ: ['so'],
  た: ['ta'],
  ち: ['ti', 'chi'],
  つ: ['tu', 'tsu'],
  て: ['te'],
  と: ['to'],
  な: ['na'],
  に: ['ni'],
  ぬ: ['nu'],
  ね: ['ne'],
  の: ['no'],
  は: ['ha'],
  ひ: ['hi'],
  ふ: ['hu', 'fu'],
  へ: ['he'],
  ほ: ['ho'],
  ま: ['ma'],
  み: ['mi'],
  む: ['mu'],
  め: ['me'],
  も: ['mo'],
  や: ['ya'],
  ゆ: ['yu'],
  よ: ['yo'],
  ら: ['ra'],
  り: ['ri'],
  る: ['ru'],
  れ: ['re'],
  ろ: ['ro'],
  わ: ['wa'],
  を: ['wo'],
  が: ['ga'],
  ぎ: ['gi'],
  ぐ: ['gu'],
  げ: ['ge'],
  ご: ['go'],
  ざ: ['za'],
  じ: ['zi', 'ji'],
  ず: ['zu'],
  ぜ: ['ze'],
  ぞ: ['zo'],
  だ: ['da'],
  ぢ: ['di'],
  づ: ['du'],
  で: ['de'],
  ど: ['do'],
  ば: ['ba'],
  び: ['bi'],
  ぶ: ['bu'],
  べ: ['be'],
  ぼ: ['bo'],
  ぱ: ['pa'],
  ぴ: ['pi'],
  ぷ: ['pu'],
  ぺ: ['pe'],
  ぽ: ['po'],
  ゔ: ['vu'],

  ぁ: ['xa', 'la'],
  ぃ: ['xi', 'li', 'xyi', 'lyi'],
  ぅ: ['xu', 'lu'],
  ぇ: ['xe', 'le', 'xye', 'lye'],
  ぉ: ['xo', 'lo'],
  ゃ: ['xya', 'lya'],
  ゅ: ['xyu', 'lyu'],
  ょ: ['xyo', 'lyo'],
  ゎ: ['xwa', 'lwa'],
  っ: ['xtu', 'ltu', 'ltsu'],

  きゃ: ['kya'],
  きぃ: ['kyi'],
  きゅ: ['kyu'],
  きぇ: ['kye'],
  きょ: ['kyo'],
  ぎゃ: ['gya'],
  ぎぃ: ['gyi'],
  ぎゅ: ['gyu'],
  ぎぇ: ['gye'],
  ぎょ: ['gyo'],
  しゃ: ['sya', 'sha'],
  しぃ: ['syi'],
  しゅ: ['syu', 'shu'],
  しぇ: ['sye', 'she'],
  しょ: ['syo', 'sho'],
  じゃ: ['ja', 'zya', 'jya'],
  じぃ: ['zyi', 'jyi'],
  じゅ: ['ju', 'zyu', 'jyu'],
  じぇ: ['je', 'zye', 'jye'],
  じょ: ['jo', 'zyo', 'jyo'],
  ちゃ: ['tya', 'cha', 'cya'],
  ちぃ: ['tyi', 'cyi'],
  ちゅ: ['tyu', 'chu', 'cyu'],
  ちぇ: ['tye', 'che', 'cye'],
  ちょ: ['tyo', 'cho', 'cyo'],
  ぢゃ: ['dya'],
  ぢぃ: ['dyi'],
  ぢゅ: ['dyu'],
  ぢぇ: ['dye'],
  ぢょ: ['dyo'],
  にゃ: ['nya'],
  にぃ: ['nyi'],
  にゅ: ['nyu'],
  にぇ: ['nye'],
  にょ: ['nyo'],
  ひゃ: ['hya'],
  ひぃ: ['hyi'],
  ひゅ: ['hyu'],
  ひぇ: ['hye'],
  ひょ: ['hyo'],
  びゃ: ['bya'],
  びぃ: ['byi'],
  びゅ: ['byu'],
  びぇ: ['bye'],
  びょ: ['byo'],
  ぴゃ: ['pya'],
  ぴぃ: ['pyi'],
  ぴゅ: ['pyu'],
  ぴぇ: ['pye'],
  ぴょ: ['pyo'],
  みゃ: ['mya'],
  みぃ: ['myi'],
  みゅ: ['myu'],
  みぇ: ['mye'],
  みょ: ['myo'],
  りゃ: ['rya'],
  りぃ: ['ryi'],
  りゅ: ['ryu'],
  りぇ: ['rye'],
  りょ: ['ryo'],

  ふぁ: ['fa', 'fwa'],
  ふぃ: ['fi', 'fwi', 'fyi'],
  ふぅ: ['fwu'],
  ふぇ: ['fe', 'fwe', 'fye'],
  ふぉ: ['fo', 'fwo'],
  ふゃ: ['fya'],
  ふゅ: ['fyu'],
  ふょ: ['fyo'],
  うぁ: ['wha'],
  うぃ: ['wi', 'whi'],
  うぇ: ['we', 'whe'],
  うぉ: ['who'],
  いぇ: ['ye'],
  ゔぁ: ['va'],
  ゔぃ: ['vi', 'vyi'],
  ゔぇ: ['ve', 'vye'],
  ゔぉ: ['vo'],
  ゔゃ: ['vya'],
  ゔゅ: ['vyu'],
  ゔょ: ['vyo'],
  てゃ: ['tha'],
  てぃ: ['thi'],
  てゅ: ['thu'],
  てぇ: ['the'],
  てょ: ['tho'],
  でゃ: ['dha'],
  でぃ: ['dhi'],
  でゅ: ['dhu'],
  でぇ: ['dhe'],
  でょ: ['dho'],
  つぁ: ['tsa'],
  つぃ: ['tsi'],
  つぇ: ['tse'],
  つぉ: ['tso'],
  とぁ: ['twa'],
  とぃ: ['twi'],
  とぅ: ['twu'],
  とぇ: ['twe'],
  とぉ: ['two'],
  どぁ: ['dwa'],
  どぃ: ['dwi'],
  どぅ: ['dwu'],
  どぇ: ['dwe'],
  どぉ: ['dwo'],
  くぁ: ['qa', 'kwa', 'qwa'],
  くぃ: ['qi', 'qwi', 'qyi'],
  くぅ: ['qwu'],
  くぇ: ['qe', 'qwe', 'qye'],
  くぉ: ['qo', 'qwo'],
  くゃ: ['qya'],
  くゅ: ['qyu'],
  くょ: ['qyo'],
  ぐぁ: ['gwa'],
  ぐぃ: ['gwi'],
  ぐぅ: ['gwu'],
  ぐぇ: ['gwe'],
  ぐぉ: ['gwo'],
  すぁ: ['swa'],
  すぃ: ['swi'],
  すぅ: ['swu'],
  すぇ: ['swe'],
  すぉ: ['swo'],

  ー: ['-'],
  '、': [','],
  '。': ['.'],
  '・': ['/'],
  '「': ['['],
  '」': [']'],
  '！': ['!'],
  '？': ['?'],
}

export const KANA_TABLE: ReadonlyMap<string, readonly string[]> = new Map(
  Object.entries(table),
)

export const MAX_CHUNK = 2
